---
title: "Homework 5"
author: "Lauren Berkley"
date: "2/16/2022"
output:
  html_document:
    theme: journal
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Link to [Home](index.html)

### Question 1

```{r}
# Assign to the variable n_dims a single random integer between 3 and 10.
n_dims <- floor(runif(1, min = 3, max = 10))
print(n_dims)

# Create a vector of consecutive integers from 1 to n_dims^2.
next_vector <- seq(1:n_dims^2)
print(next_vector)

# Use the sample function to randomly reshuffle these values.
sample(next_vector)

# Create a square matrix with these elements.
my_matrix <- matrix(next_vector, nrow = n_dims, byrow = TRUE)

# Print out the matrix.
print(my_matrix)

# Find a function in r to transpose the matrix. I found the function transpose which is t(matrix).
transposed_matrix <- t(my_matrix)

# Print it out again and note how it has changed.
print(transposed_matrix)

# Calculate the sum and the mean of the elements in the first row and the last row.

## Sum
### First row
sum(transposed_matrix[1,])
### Last row
sum(transposed_matrix[n_dims,])

## Mean
### First row
mean(transposed_matrix[1,])
### Last row
mean(transposed_matrix[n_dims,])

# Read about the eigen() function and use it on your matrix.
eigen_lists <- eigen(transposed_matrix, only.values = FALSE, EISPACK = FALSE)
print(eigen_lists)

# Look carefully at the elements of $values and $vectors. What kind of numbers are these?
## complex numbers

# Dig in with the typeof() function to figure out their type.
typeof(eigen_lists $ values)
typeof(eigen_lists $ vectors)

# If have set your code up properly, you should be able to re-run it and create a matrix of different size because n_dims will change.
## Yep!
```

### Question 2

```{r}
# Create a list with the following named elements:
# my_matrix, which is a 4 x 4 matrix filled with random uniform values
# my_logical which is a 100-element vector of TRUE or FALSE values. Do this efficiently by setting up a vector of random values and then applying an inequality to it.
# my_letters, which is a 26-element vector of all the lower-case letters in random order.

my_matrix <- matrix(runif(16), nrow = 4, byrow = TRUE)
print(my_matrix)

my_logical <- runif(100) < 0.5
print(my_logical)

my_letters <- sample(letters[seq(1:26)])
print(my_letters)

my_list <- c(my_matrix, my_logical, my_letters)
print(my_list)

# Create a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector.

my_new_list <- list(my_matrix[2,2], my_logical[2], my_letters[2])
print(my_new_list)

# Use the typeof() function to confirm the underlying data types of each component in this list

typeof(my_new_list[[1]])
typeof(my_new_list[[2]])
typeof(my_new_list[[3]])

# Combine the underlying elements from the new list into a single atomic vector with the c() function.
my_new_vector <- c(my_matrix[2,2], my_logical[2], my_letters[2])
print(my_new_vector)

# What is the data type of this vector?
typeof(my_new_vector)
```

### Question 3
```{r}
# Create a data frame with two variables (= columns) and 26 cases (= rows).
# call the first variable my_unis and fill it with 26 random uniform values from 0 to 10
# call the second variable my_letters and fill it with 26 capital letters in random order.

my_unis <- runif(26, min = 0, max = 10)
my_letters <- sample(LETTERS[seq(1:26)])

my_data_frame <- data.frame(my_unis, my_letters)
print(my_data_frame)

# for the first variable, use a single line of code in R to select 4 random rows and replace the numerical values in those rows with NA.
my_data_frame[,1] <- replace(x = my_data_frame[,1], list = sample(nrow(my_data_frame),4), values = NA)

# for the first variable, write a single line of R code to identify which rows have the missing values.
which(is.na(my_data_frame))

# for the second variable, sort it in alphabetical order
my_data_frame[,2] <- sort(my_data_frame[,2], decreasing = FALSE)
print(my_data_frame)

#calculate the column mean for the first variable
mean(which(complete.cases(my_data_frame)))
```



