---
title: "Homework 9"
author: "Lauren Berkley"
date: "3/23/2022"
output:
    html_document:
      theme: journal
      toc: true
      toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Link to [Home](index.html)

```{r}
# Description -----------------------------------
# This is a script for Homework 9. I am using the data from Homework 8. I am going to focus on my predictions for the infection rate of Plasmodium odocoilei in white tailed deer. Based on previous research, I hypothesize that white-tailed deer across Vermont, New Hampshire, and Maine are infected with Plasmodium odocoilei at a rate of about 25%.

# 23 Mar 2022
# LEB

# Initialize ------------------------------------
library(tidyverse)

# Load Functions --------------------------------

library(boot)
library(ggplot2)
library(broom)

# Global Variables ------------------------------

VT <- inv.logit(rnorm(n=500,mean=0.25,sd=.50))
NH <- inv.logit(rnorm(n=500,mean=0.25,sd=.50))
ME <- inv.logit(rnorm(n=500,mean=0.25,sd=.50))

# Program Body ----------------------------------

Fake_Deer_Data <- sim_deer_data() # create fake data frame
head(Fake_Deer_Data)

pred <- temp1[,x_col] # extract predictor variable
res <- temp1[,y_col] # extract response variable

temp2 <- calculate_stuff(x_var=pred,y_var=res)
temp3 <- summarize_output(temp2)

graph_results(x_var=pred,y_var=res) # create graph

print(temp2) # shows model summary
print(temp3) # residuals from the regression

get_data()
calculate_stuff()
summarize_output()
graph_results()
```


```


