---
title: "Homework 7"
author: "Lauren Berkley"
date: "3/2/2022"
output:
    html_document:
      theme: journal
      toc: true
      toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Link to [Home](index.html)

### Intro to `dplyr`
```{r}
# Examine the structure of the iris dataset. How many observations and variables are in the dataset?
library(tidyverse)
data(iris)
class(iris)
glimpse(iris)

# Create a new data frame iris1 that contains only the species virginica and versicolor with sepal lengths longer than 6 cm and sepal widths longer than 2.5 cm. How many observations and variables are in the dataset?

iris1 <- filter(iris, Species == "virginica" | Species == "versicolor", Sepal.Length > 6, Sepal.Width > 2.5)
glimpse(iris1)

# Now, create a iris2 data frame from iris1 that contains only the columns for Species, Sepal.Length, and Sepal.Width. How many observations and variables are in the dataset?

iris2 <- select(iris1, Species | Sepal.Length | Sepal.Width)
glimpse(iris2)

# Create an iris3 data frame from iris2 that orders the observations from largest to smallest sepal length. Show the first 6 rows of this dataset.

iris3 <- arrange(iris2, by = desc(Sepal.Length))
iris3[1:6,]

# Create an iris4 data frame from iris3 that creates a column with a sepal area (length * width) value for each observation. How many observations and variables are in the dataset?

iris4 <- mutate(iris3, Sepal.Area = Sepal.Length*Sepal.Width)
glimpse(iris4)

# Create iris5 that calculates the average sepal length, the average sepal width, and the sample size of the entire iris4 data frame and print iris5

iris5 <- summarize(iris4, Average.Sepal.Length = mean(Sepal.Length), Average.Sepal.Width = mean(Sepal.Width), Sample.Size = n())
print(iris5)

# Finally, create iris6 that calculates the average sepal length, the average sepal width, and the sample size for each species of in the iris4 data frame and print iris6

Iris.Species <- group_by(iris4,Species)
iris6 <- summarize(Iris.Species, Average.Sepal.Length = mean(Sepal.Length), Average.Sepal.Width = mean(Sepal.Width), Sample.Size = n())
print(iris6)
```

### Piping!
```{r}
# In these exercises, you have successively modified different versions of the data frame iris1 iris1 iris3 iris4 iris5 iris6. At each stage, the output data frame from one operation serves as the input fro the next. A more efficient way to do this is to use the pipe operator %>% from the tidyr package. See if you can rework all of your previous statements into an extended piping operation that uses iris as the input and generates iris6 as the output.

library(tidyverse)
data(iris)

iris %>%
  filter(Species == "virginica" | Species == "versicolor", Sepal.Length > 6, Sepal.Width > 2.5) %>%
  select(Species | Sepal.Length | Sepal.Width) %>%
  arrange(by = desc(Sepal.Length)) %>%
  mutate(Sepal.Area = Sepal.Length*Sepal.Width) %>%
  group_by(Species) %>%
  summarize(Average.Sepal.Length = mean(Sepal.Length), Average.Sepal.Width = mean(Sepal.Width), Sample.Size = n())
```

### Making the data longer
```{r}
# Create a ‘longer’ data frame with three columns named: Species, Measure, Value

library(tidyverse)
data(iris)

longIris <- iris %>%
  pivot_longer(cols= Sepal.Length:Petal.Width,
               names_to = "Measure",
               values_to= "Value",
               values_drop_na = T)

print(longIris)

```

